### PR TITLE
The explode component expires continuously if an input with an empty structure is plugged in

### LINKED ISSUE #311: Grasshopper_Toolkit: Component creation location
The components created via the ctrl+shift+b search menu are appearing on the place of the screen where the inputs are chosen, rather than on the position of the mouse when the menu was first created. 
The second behaviour is how the standard double click menu behaves, and I think that is better, as you have no control over where the component ends up with the current implementation, and it can even appear off screen.

Gif below showing first standard GH double click behaviour, then ctrl+shift+b search menu behaviour

search menu

### LINKED ISSUE #417: Grasshopper_Toolkit: Explode component handling no data
#### Description:
The explode component is unable to handle 'no data', as a result it freezes out the 'undo' functionally. 

#### How to replicate:
image
Then try to undo

#### Expected behaviour:
The undo functionality should still be accessible

### LINKED ISSUE #419: Grasshopper_Toolkit: CreateType loses its banner
#### Description:
CreateType component has a little banner to show the selection, which dissapears after re-opening the GH definition or copying and pasting the component.

Both of these components have a type selected

#### How to replicate:

1. place a CreateType component on the canvas
2. select a type
3. save the definition
4. close the definition
5. reopen the definition

or:

1. place a CreateType component on the canvas
2. select a type
3. copy the component
4. paste the component

#### Expected behaviour:
the banner should remain visible

#### Test file(s):
oh come on, you can do it :)

### PR DESCRIPTION
**Pull request by epignatelli**
### Issues addressed by this PR

Closes #417
Closes #419 
Closes #311 (Bonus!!!! 🏆 )

### Test files 

For #417: (review by @jdarcyBHE  && (@alelom || @IsakNaslundBh)) :heavy_check_mark:
1. Create a `Data` parameter
1. Create and `Explode` component
1. Plug `Data` into `Explode` now do any other thing
1. Try to CTRL + Z 
1. Check that it can undo what you have done at point 3.

For #419 (review by @JosefTaylor )
1.  Create a `CreateType` component
1. Select a `Type`
1. Copy and paste the component
1. Check that it still shows the banner with the type

For #311: (review by @FraserGreenroyd )
Follow the procedure illustrated by @IsakNaslundBh in [this gif](https://github.com/BHoM/Grasshopper_Toolkit/issues/311#issue-396476688)

### Changelog

- Make sure that `Explode` does not refresh continuously if an empty structure is plugged in
- `CreateType` maintains the banner now after serialisation/deserialisation routines
- Component is now created where the menu first appears, rather than where the mouse cursor is

### Additional comments

@IsakNaslundBh @alelom putting you in as reviewer because this can potentially be quite dangerous. Would you mind just opening some scripts that you use and check that the `Explode` works properly?

@JosefTaylor Can you check #419 is fixed?

I added comments on who should review what to make it easier to coordinate.
If the review is successfull, you can give a green tick and add the `do-not-merge` label.
I'll take care of coordinating all the green/red ticks.

### CODE REVIEW

**Comment by epignatelli** [comment]
Thanks @FraserGreenroyd ! Not sure when a `ComponentRequest` returns a `null` `Location`, so I couldn't test it. I added a couple null checks there though, would you mind testing it?

**Comment by epignatelli** [comment]
I think as @IsakNaslundBh pointed out, we still have problems converting the coordinates from screen coordinates to canvas coordinates.
I am about to fix this.

**Comment by epignatelli** [comment]
Alright, it should be fixed now.  I promise that's the last time I ask you to review.

@JosefTaylor I aim at mergin this tomorrow all is ok. Can you please review the fix to the issue you raised?

**Comment by FraserGreenroyd** [comment]
> I promise that's the last time I ask you to review.

If you don't like bad press, stop inviting the reporters right? 😆

**Comment by IsakNaslundBh** [comment]
Think the major problem is fixed now with screen position and works better than before. When searching for a method, then selecting it with the mouse, all seems as expected now.
One thing I found is that if you pick the component using the arrow keys, it ends up wherever your mouse pointer is:
Screen position update

**Comment by epignatelli** [comment]
Thanks @IsakNaslundBh ! I think that one belongs to the the BHoM_UI. 
Whenever you use the keyboard the `ComponentRequest.Location` is `null`, which is the use case that @FraserGreenroyd discovered crashing at the beginning. 

I'll fix that in the BHoM_UI.

**Comment by jdarcyBHE** [comment]
#311 Carried out test case, and was able to undo explode connection to data container.

**Comment by epignatelli** [comment]
Thanks @jdarcyBHE ! if your're happy with the changes can you approve the pr?

**Comment by IsakNaslundBh** [comment]
And here we go!!!!
Screen position working

**Comment by epignatelli** [comment]
Thanks @IsakNaslundBh ! 
I think that's in tandem with https://github.com/BHoM/BHoM_UI/pull/174
If the keyboard request works, would you mind approving that one as well?

**Pull request merged**
