### PR TITLE
Add the link to the new RunCode component

### LINKED ISSUE #585: Missing icon for Cluster2Node component
Need to create and add new icon for **Cluster2Node**

@adecler - now's a good time to review our general icon assets actually to just tie into the rest of the BHoM logos, iconography, website material etc. 

perhaps you and I grab a quick session to coordinate? 😄

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
https://github.com/BHoM/BHoM_UI/pull/352

   
### Issues addressed by this PR

Exposes https://github.com/BHoM/BHoM_UI/pull/352 to Grasshopper

Closes #585 
Since I was creating an icon for the `RunCode` component, I thought I might as well do one for the `ClusterToNode` component as well. My artistic skills are what they are but this is admittedly better than an empty icon 😋 

### Test files
Tested at the same time as the BHoM_UI PR so check there for details.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Review by rolyhudson — APPROVED** [review]
See my notes [here](https://github.com/BHoM/BHoM_UI/pull/352#issuecomment-756271377) on the experience of using this handy prototype .

**Comment by adecler** [comment]
@BHoMBot check installer

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Pull request merged**
