### PR TITLE
Mark non-curated components with a prototype label

### LINKED ISSUE #631: Non-curated components should be marked as prototypes
#### Description:
See this for more details: https://burohappold.sharepoint.com/:p:/r/sites/Direction/designtechnology/RandDWishlist/00259_Plugins%20for%20the%20BHoM/Plugins%20for%20the%20BHoM.pptx?d=w12536d5d017c4c14a639cdad31ad48c9&csf=1&web=1&e=ljRJkd

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
https://github.com/BHoM/BHoM_Engine/pull/2590

   
### Issues addressed by this PR

Closes #631

Requires the file containing the list of curated assemblies for testing. @FraserGreenroyd , I have placed your file containing the list of dlls here: `C:\ProgramData\BHoM\Settings\IncludedDlls.txt`

### Test files
Any components can be used for testing as long as some are part of the installer and some are not. Here's an example of what to expect:

image

### Additional comments
The yellow background behind the strips was a bit of an issue due to the rounded edges of the component so I didn't include it. Personally, I actually prefer it that way as it clashes less visually. I found that matching the color of the strips with the color of the component's border had the best visual effect.

### CODE REVIEW

**Review by FraserGreenroyd — COMMENTED** [review]
See [this review](https://github.com/BHoM/BHoM_Engine/pull/2590#pullrequestreview-726485114)

**Comment by IsakNaslundBh** [comment]
After chat with @adecler , changed the grabbing of the colour to use the same system that is being used by the standard GH component rendering

image

**Review by FraserGreenroyd — APPROVED** [review]
See [this review](https://github.com/BHoM/BHoM_Engine/pull/2590#pullrequestreview-727339278)

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check copyright-compliance

**Pull request merged**
