### PR TITLE
Add detection of incorrect group structure in Node2Code

### LINKED ISSUE #478: The order groups are created matters (even if resulting grouping topology is the same)
See examples below. The numbers highlighting the order I created the groups. You can see the resulting code is affected - and in the second case invalid.

#### Order 1
Node2Code2

#### Order 2
Node2Code3

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #478

Takes care of the situation where the groups were created incorrectly resulting in descriptions or components appearing in multiple groups.

### Additional comments
I went a bit overboard with potential cases that are actually not possible in Grasshopper but that was done expecting to move some of the code more centrally (i.e. outside of GH TK)

### CODE REVIEW

**Comment by adecler** [comment]
@al-fisher , please let me know if you don't think you will have the time to review this before Friday.

**Comment by al-fisher** [comment]
I’ll jump on this tomorrow 
Thanks @adecler

**Comment by al-fisher** [comment]
I am sorry @adecler - I did not manage to get to this today 😿

**Comment by al-fisher** [comment]
FYI @adecler & @FraserGreenroyd you can see from above I have just turned on the standard core required Checks for Grasshopper now as well.

**Pull request merged**
