### PR TITLE
Fix Enum display

### LINKED ISSUE #569: Enum display not displaying value
image

Should be:

image

Seems to be the case for any enum, it is displaying the type of the enum rather than the value. Second screenshot is from Monday's Alpha, first one from today's (Friday).

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #569 

### Test files
Output generated from today's Alpha with this PR built on top.
image

@adecler this is a patch that seemed to work, but might not be the right place for it in which case my apologies, please feel free to advise on correct placement.

Thanks to @IsakNaslundBh for assisting in undertaking this as well! :smile:

### CODE REVIEW

**Review by IsakNaslundBh — CHANGES_REQUESTED** [review]
Works fine: 
image

Can we just add a last comment line, please.

After that, I would be happy to approve, but will not merge until @adecler has had a look at it

**Review by IsakNaslundBh — APPROVED** [review]
Now LGTM. Again, will leave it to @adecler to say if this is the right way to deal with this.

**Comment by FraserGreenroyd** [comment]
Have run CheckInstaller just in case @adecler is happy so he doesn't have to wait to hit merge :smile:

**Review by adecler — CHANGES_REQUESTED** [review]
This is the wrong repo to fix this.
This should be handled in `BH.Engine.Reflection.IToText()`.

See `GH_BHoMGoo<T>.ToString()` for reference.

**Comment by FraserGreenroyd** [comment]
Have raised [this PR](https://github.com/BHoM/BHoM_Engine/pull/2195) to replace this one, am closing and deleting branch for this PR.

**Pull request closed without merging**
