### PR TITLE
Render basic graphical objects

### LINKED ISSUE #601: Render basic graphical objects
#### Description:
Support rendering of basic graphical objects described in https://github.com/BHoM/BHoM/issues/1190.

### PR DESCRIPTION
**Pull request by rolyhudson**
### NOTE: Depends on 
https://github.com/BHoM/Rhinoceros_Toolkit/pull/202
https://github.com/BHoM/BHoM/pull/1191

   
### Issues addressed by this PR

Closes #601

### CODE REVIEW

**Review by alelom — APPROVED** [review]
LGTM!

**Comment by rolyhudson** [comment]
@BHoMBot check all

**Comment by rolyhudson** [comment]
@BHoMBot check core

**Comment by IsakNaslundBh** [comment]
@BHoMBot check code-copyright

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright

**Pull request merged**
