### PR TITLE
Fix the pre-existing note messages covering the warnings

### LINKED ISSUE #541: Message notes cover all other messages again
#### Description:

We have again the same behaviour described in https://github.com/BHoM/Grasshopper_Toolkit/issues/480
that was fixed in https://github.com/BHoM/Grasshopper_Toolkit/pull/490.

#### Steps to reproduce:

Have any grasshopper component return a Note and additionally a Warning and/or an Error.
The Note colour will prevail, as described in https://github.com/BHoM/Grasshopper_Toolkit/issues/480.

#### Expected behaviour:

Note should not cover. Same behaviour obtained thanks to https://github.com/BHoM/Grasshopper_Toolkit/pull/490.

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #541

pre-existing messages are simply cleared from the component and reprocessed alongside any new event.

### Test files
https://burohappold.sharepoint.com/:u:/s/BHoM/EaLHWrCr9NVBoz76ubs8DKwBoU2QMt6dd6j4IE8EsbRoug?e=rYww0U

You might have to change the path of the file you want to download if that one is not available for you. You will find that in the `Create Download command...using a known File Full URL` section of the script.

https://burohappold.sharepoint.com/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/Versioning_Toolkit/Versioning_Toolkit.gh

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check all

**Review by alelom — APPROVED** [review]
Works! Fixes the bug for me:
image

Thanks!

**Comment by adecler** [comment]
@BHoMBot check ready-merge

**Comment by adecler** [comment]
@FraserGreenroyd , help please 😋 

Not sure I see the point of that check is if I am honest. Isn't the PR allowed to merged only once it is approved by at least one person anyways ?

**Pull request merged**
