### PR TITLE
Add support for render texture

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1389
https://github.com/BHoM/Rhinoceros_Toolkit/pull/227
   
### Issues addressed by this PR

Add support for the changes to RenderGeometry

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Graphics_oM/%231389-AddGraphsicsRenderTexture?csf=1&web=1&e=NxVT3M

### CODE REVIEW

**Review by michaelhoehn — APPROVED** [review]
I've tested and approved this feature. LGTM!

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core
@BHoMBot check null-handling

**Comment by IsakNaslundBh** [comment]
@BHoMBot check serialisation

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 6622642722

**Pull request merged**
