### PR TITLE
Remove the RunCode component

### LINKED ISSUE #614: Removal of RunCode functionality from main branch/alpha/betas
As discussed need and user story mapping needs to take place before any work on the RunCode component is carried out and as such the current prototype is not ready for deployment in installers.

Access should be removed from Grasshopper menu to avoid confusion for users.
image

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
https://github.com/BHoM/BHoM_UI/pull/380

   
### Issues addressed by this PR

Closes #614

The code is now stored in the `RunCodeComponent` branch.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by FraserGreenroyd — APPROVED** [review]
RunCode component no longer showing up so LGTM.

I've asked @pawelbaran to confirm the Dynamo issue with the installer generated by the check. @pawelbaran can you make a note on here with your findings :smile:

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by rolyhudson** [comment]
I'm not tagged as a reviewer. But out of respect to `RunCode` I have reviewed and confirm, sadly, it is gone (from grasshopper) RIP.
`RunCode` is dead. Long live `RunCode` 🤣 we'll see you in the next life

**Comment by FraserGreenroyd** [comment]
Confirmed with @pawelbaran that the installer is resolved with these PRs for beta so am now merging these ready for further alpha testing and beta testing next sprint.

**Pull request merged**
