### PR TITLE
Add unitTest component

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_UI/pull/356
   
### Issues addressed by this PR

See https://github.com/BHoM/BHoM_UI/pull/356 for details. This is simply adding a component corresponding to the added caller.

### CODE REVIEW

**Review by adecler — CHANGES_REQUESTED** [review]
The file should be called `UnitTest`, not `UnitTestComponent`

**Review by adecler — APPROVED** [review]

**Comment by IsakNaslundBh** [comment]
@BHoMBot check code copyright

**Comment by IsakNaslundBh** [comment]
@BHoMBot check code copyright

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright

**Review by JohannaOlin1 — APPROVED** [review]
Worked for me when added unit test for MapRegions

**Review by FraserGreenroyd — APPROVED** [review]
LGTM

**Pull request merged**
