### PR TITLE
Add a Query method to get the currently active canvas file path

### LINKED ISSUE #521: Add method to return the filepath of the currently open Grasshopper script
#### Description:

As discussed with @rwemay. This can be useful to uniform the scripts. We often save script files and share them, and every time we need to edit the filepath which is usually internalised in a Panel.

```cs
 GH_Document ghDoc = owner.OnPingDocument();
    if (ghDoc.IsFilePathDefined)
      A = ghDoc.FilePath;
```

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #521

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Review by jamesramsden-bh — APPROVED** [review]
Compiled and tested against unsaved file, saved file and reopened saved file. All behaviour as expected.

**Pull request merged**
