### PR TITLE
Adding UI Setting with ability to disable wire menu

### LINKED ISSUE #645: Add option to disable intellisense on dragged wires
#### Description:
This was raised during the AEC Tech hack. Some users would like a feature to disable the wire-drag intellisense, as they found it intrusive when not using BHoM components. Suggest we flag as high priority, as it sounds like it is getting in the way of some users adopting BHoM into their computational toolchest.

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #645

As discussed, no fancy menu at the moment. But a fairly simple way to set Grasshopper UI settings using the existing infrastructure for settings.

### Test files
Simply create those components on the canvas and toggle the boolean to activate or deactivate the wire menu:

GrasshopperSettings_Demo

### CODE REVIEW

**Comment by adecler** [comment]
@BHombot check compliance

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot fix copyright headers ref. 4235551014

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot fix project file ref. 4306798044

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance

**Comment by adecler** [comment]
@BHoMBot check compliance

**Comment by adecler** [comment]
@BHoMBot fix copyright headers ref. 4862097413

**Comment by adecler** [comment]
@BHoMBot check compliance

**Comment by adecler** [comment]
@BHoMBot check required

**Review by IsakNaslundBh — APPROVED** [review]
Works as expected!

**Comment by adecler** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
