### PR TITLE
Adding support for RenderCurve

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1385
https://github.com/BHoM/Rhinoceros_Toolkit/pull/222
   
### Issues addressed by this PR

https://github.com/BHoM/BHoM/issues/1271

Adding support for displaying RenderCurves

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Graphics_oM/Graphics_oM-%231271-AddRenderCurve?csf=1&web=1&e=Uvpn7O

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Review by al-fisher — APPROVED** [review]
Approving this as part of chain of PRs adding RenderCurve.

Tested based on provided test script. Approving based on functionality.
Looks good. Great to get this capability in 👍

**Pull request merged**
