### PR TITLE
Add new reference to CodeEditor_UI

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
https://github.com/BHoM/BHoM_UI/pull/359

   
### Issues addressed by this PR

With the RunCode component moved to its own dll, this PR keeps that component working by referencing the new dll.

### Test files
Just make sure the RunCode component is still working.

### Additional comments
@Fraser, I had to recompile the CSharp toolkit for the editor to open after I selected an item on the RunCode component. I found that a bit strange. Is the CSharp toolkit not distributed with the installer ?

### CODE REVIEW

**Review by pawelbaran — APPROVED** [review]
LGTM 👍

**Comment by fraser** [comment]
@adecler btw, I think you mentioned the wrong fraser.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project compliance

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
Copy local fixes please :smile:

Otherwise LGTM

**Comment by adecler** [comment]
@BHoMBot check project compliance

**Comment by adecler** [comment]
@BHoMBot check copyright installer

**Comment by adecler** [comment]
@BHoMBot check installer

**Review by pawelbaran — APPROVED** [review]
Still LGTM 👍

**Review by FraserGreenroyd — APPROVED** [review]
LGTM

**Pull request merged**
